export type ArtworkCategory = (typeof ARTWORK_CATEGORIES)[number];
export const ARTWORK_CATEGORIES = Object.freeze([
    "kitsune",
    "neko",
    "husbando",
    "waifu",
] as const);

export type RoleplayCategory = (typeof ROLEPLAY_CATEGORIES)[number];
export const ROLEPLAY_CATEGORIES = Object.freeze([
    "angry",
    "baka",
    "bite",
    "bleh",
    "blowkiss",
    "blush",
    "bonk",
    "bored",
    "carry",
    "clap",
    "confused",
    "cry",
    "cuddle",
    "dance",
    "facepalm",
    "feed",
    "handhold",
    "handshake",
    "happy",
    "highfive",
    "hug",
    "kabedon",
    "kick",
    "kiss",
    "lappillow",
    "laugh",
    "lurk",
    "nod",
    "nom",
    "nope",
    "nya",
    "pat",
    "peck",
    "poke",
    "pout",
    "punch",
    "run",
    "salute",
    "shake",
    "shocked",
    "shoot",
    "shrug",
    "sip",
    "slap",
    "sleep",
    "smile",
    "smug",
    "spin",
    "stare",
    "tableflip",
    "teehee",
    "think",
    "thumbsup",
    "tickle",
    "wag",
    "wave",
    "wink",
    "yawn",
    "yeet",
] as const);

export type Category = (typeof CATEGORIES)[number];
export const CATEGORIES = Object.freeze([
    ...ARTWORK_CATEGORIES,
    ...ROLEPLAY_CATEGORIES,
]);
