/** @package */
export const CATEGORIES = Object.freeze({
    GIF: Object.freeze([
        "baka",
        "bite",
        "blush",
        "bored",
        "cry",
        "cuddle",
        "dance",
        "facepalm",
        "feed",
        "handhold",
        "handshake",
        "happy",
        "highfive",
        "hug",
        "kick",
        "kiss",
        "laugh",
        "lurk",
        "nod",
        "nom",
        "nope",
        "pat",
        "peck",
        "poke",
        "pout",
        "punch",
        "shoot",
        "shrug",
        "slap",
        "sleep",
        "smile",
        "smug",
        "stare",
        "think",
        "thumbsup",
        "tickle",
        "wave",
        "wink",
        "yawn",
        "yeet",
    ] as const),

    PNG: Object.freeze([
        "husbando",
        "kitsune",
        "neko",
        "waifu",
    ] as const),
});
